### ISSUE TITLE
considering refactor of makara* langpack building family

### ISSUE THREAD

**Issue by grawk** [krakenjs/makara-browserify#1]
`makara-browserify` and `makara-amdify` look to be essentially identical, save for their private "streamLocale" methods in their build modules and minor differences between the other two exported functionalities (languagepackPath, middleware)

**makara-browserify**: https://github.com/krakenjs/makara-browserify/blob/v1.x/build.js#L29-L43

**makara-amdify**: https://github.com/krakenjs/makara-amdify/blob/v1.x/build.js#L28-L37

Considering renaming parent module to something like "makara-builder", have it depend on two modules "makara-amdify" and "makara-browserify" which will have the specific implementations necessary for outputting the languagepack files, as well as any other differences between amd and browserify in the remaining API (languagepackPath, middleware)

Benefits are:
- breaks out the amd and browserify file writing to discrete modules which can then be consumed by other modules which wish to write such files in a different workflow than "makara-builder" (such as construx plugins for writing amd or browserify locale modules on the fly)

**Comment by aredridel** [comment]
Should it depend on those packages, or those packages depend on it?

**Comment by aredridel** [comment]
And yes, this sounds like a good approach.

**Comment by grawk** [comment]
I see what you mean. How about this:
both the "build" module as well as the "streamLocale" function can be separate modules which are consumed by the existing makara-amdify and makara-browserify. There should only be need of a single build module, while streamLocale will have amd and browserify flavors.

**Comment by aredridel** [comment]
Makes sense! And that way, looking at an app's dependencies, you can see what is connected to what.

**Comment by grawk** [comment]
names:
- `makara-writer-amd`
- `makara-writer-browserify`
- `makara-builder`

?

**Comment by aredridel** [comment]
Sure -- though could keep the existing names. `makara-amdify`, `makara-browserify`, and add `makara-builder` that they depend on.

**Comment by grawk** [comment]
Sorry for not being complete. Yes I want to keep `makara-amdify` and `makara-browserify` as the parent modules. each will depend on `makara-builder` and appropriate `*writer*` module. And the interface to both parent modules will remain unchanged.

**Comment by aredridel** [comment]
Oh! I see. Yeah, makes total sense. So they become tiny shims that tie together a couple pieces.

**Comment by grawk** [comment]
resolved with publish of `makara-builder@2` and associated patches of `makara-browserify@1.2.6` and `makara-amdify@1.1.8`.
